version: "3.8"

services:
  backend:
    build:
      context: ./backend/ticket-booking-backend/ticket-booking-backend
    container_name: ticket-booking-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/ticketdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tiger140105
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/frontend
    container_name: ticket-booking-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped